export const currencies = [
  { value: "EUR", label: "Andorra - EUR" },
  { value: "AED", label: "United Arab Emirates - AED" },
  { value: "AFN", label: "Afghanistan - AFN" },
  { value: "XCD", label: "Antigua and Barbuda - XCD" },
  { value: "XCD", label: "Anguilla - XCD" },
  { value: "ALL", label: "Albania - ALL" },
  { value: "AMD", label: "Armenia - AMD" },
  { value: "AOA", label: "Angola - AOA" },
  { value: "ARS", label: "Argentina - ARS" },
  { value: "USD", label: "American Samoa - USD" },
  { value: "EUR", label: "Austria - EUR" },
  { value: "AUD", label: "Australia - AUD" },
  { value: "AWG", label: "Aruba - AWG" },
  { value: "EUR", label: "Åland Islands - EUR" },
  { value: "AZN", label: "Azerbaijan - AZN" },
  { value: "BAM", label: "Bosnia and Herzegovina - BAM" },
  { value: "BBD", label: "Barbados - BBD" },
  { value: "BDT", label: "Bangladesh - BDT" },
  { value: "EUR", label: "Belgium - EUR" },
  { value: "XOF", label: "Burkina Faso - XOF" },
  { value: "BGN", label: "Bulgaria - BGN" },
  { value: "BHD", label: "Bahrain - BHD" },
  { value: "BIF", label: "Burundi - BIF" },
  { value: "XOF", label: "Benin - XOF" },
  { value: "EUR", label: "Saint Barthélemy - EUR" },
  { value: "BMD", label: "Bermuda - BMD" },
  { value: "BND", label: "Brunei Darussalam - BND" },
  { value: "BOB", label: "Bolivia - BOB" },
  { value: "USD", label: "Bonaire, Sint Eustatius and Saba - USD" },
  { value: "BRL", label: "Brazil - BRL" },
  { value: "BSD", label: "Bahamas - BSD" },
  { value: "BTN", label: "Bhutan - BTN" },
  { value: "NOK", label: "Bouvet Island - NOK" },
  { value: "BWP", label: "Botswana - BWP" },
  { value: "BYN", label: "Belarus - BYN" },
  { value: "BZD", label: "Belize - BZD" },
  { value: "CAD", label: "Canada - CAD" },
  { value: "AUD", label: "Cocos (Keeling) Islands - AUD" },
  { value: "CDF", label: "Democratic Republic of the Congo - CDF" },
  { value: "XAF", label: "Central African Republic - XAF" },
  { value: "XAF", label: "Republic of the Congo - XAF" },
  { value: "CHF", label: "Switzerland - CHF" },
  { value: "XOF", label: "Cote D'Ivoire - XOF" },
  { value: "NZD", label: "Cook Islands - NZD" },
  { value: "CLP", label: "Chile - CLP" },
  { value: "XAF", label: "Cameroon - XAF" },
  { value: "CNY", label: "People's Republic of China - CNY" },
  { value: "COP", label: "Colombia - COP" },
  { value: "CRC", label: "Costa Rica - CRC" },
  { value: "CUP", label: "Cuba - CUP" },
  { value: "CVE", label: "Cape Verde - CVE" },
  { value: "ANG", label: "Curaçao - ANG" },
  { value: "AUD", label: "Christmas Island - AUD" },
  { value: "EUR", label: "Cyprus - EUR" },
  { value: "CZK", label: "Czech Republic - CZK" },
  { value: "EUR", label: "Germany - EUR" },
  { value: "DJF", label: "Djibouti - DJF" },
  { value: "DKK", label: "Denmark - DKK" },
  { value: "XCD", label: "Dominica - XCD" },
  { value: "DOP", label: "Dominican Republic - DOP" },
  { value: "DZD", label: "Algeria - DZD" },
  { value: "USD", label: "Ecuador - USD" },
  { value: "EUR", label: "Estonia - EUR" },
  { value: "EGP", label: "Egypt - EGP" },
  { value: "MAD", label: "Western Sahara - MAD" },
  { value: "ERN", label: "Eritrea - ERN" },
  { value: "EUR", label: "Spain - EUR" },
  { value: "ETB", label: "Ethiopia - ETB" },
  { value: "EUR", label: "Finland - EUR" },
  { value: "FJD", label: "Fiji - FJD" },
  { value: "FKP", label: "Falkland Islands (Malvinas) - FKP" },
  { value: "USD", label: "Micronesia, Federated States of - USD" },
  { value: "DKK", label: "Faroe Islands - DKK" },
  { value: "EUR", label: "France - EUR" },
  { value: "XAF", label: "Gabon - XAF" },
  { value: "GBP", label: "United Kingdom - GBP" },
  { value: "XCD", label: "Grenada - XCD" },
  { value: "GEL", label: "Georgia - GEL" },
  { value: "EUR", label: "French Guiana - EUR" },
  { value: "GBP", label: "Guernsey - GBP" },
  { value: "GHS", label: "Ghana - GHS" },
  { value: "GIP", label: "Gibraltar - GIP" },
  { value: "DKK", label: "Greenland - DKK" },
  { value: "GMD", label: "Republic of The Gambia - GMD" },
  { value: "GNF", label: "Guinea - GNF" },
  { value: "EUR", label: "Guadeloupe - EUR" },
  { value: "XAF", label: "Equatorial Guinea - XAF" },
  { value: "EUR", label: "Greece - EUR" },
  { value: "GBP", label: "South Georgia and the South Sandwich Islands - GBP" },
  { value: "GTQ", label: "Guatemala - GTQ" },
  { value: "USD", label: "Guam - USD" },
  { value: "XOF", label: "Guinea-Bissau - XOF" },
  { value: "GYD", label: "Guyana - GYD" },
  { value: "HKD", label: "Hong Kong - HKD" },
  { value: "AUD", label: "Heard Island and McDonald Islands - AUD" },
  { value: "HNL", label: "Honduras - HNL" },
  { value: "HRK", label: "Croatia - HRK" },
  { value: "HTG", label: "Haiti - HTG" },
  { value: "HUF", label: "Hungary - HUF" },
  { value: "IDR", label: "Indonesia - IDR" },
  { value: "EUR", label: "Ireland - EUR" },
  { value: "ILS", label: "Israel - ILS" },
  { value: "GBP", label: "Isle of Man - GBP" },
  { value: "INR", label: "India - INR" },
  { value: "USD", label: "British Indian Ocean Territory - USD" },
  { value: "IQD", label: "Iraq - IQD" },
  { value: "IRR", label: "Islamic Republic of Iran - IRR" },
  { value: "ISK", label: "Iceland - ISK" },
  { value: "EUR", label: "Italy - EUR" },
  { value: "GBP", label: "Jersey - GBP" },
  { value: "JMD", label: "Jamaica - JMD" },
  { value: "JOD", label: "Jordan - JOD" },
  { value: "JPY", label: "Japan - JPY" },
  { value: "KES", label: "Kenya - KES" },
  { value: "KGS", label: "Kyrgyzstan - KGS" },
  { value: "KHR", label: "Cambodia - KHR" },
  { value: "AUD", label: "Kiribati - AUD" },
  { value: "KMF", label: "Comoros - KMF" },
  { value: "XCD", label: "Saint Kitts and Nevis - XCD" },
  { value: "KPW", label: "North Korea - KPW" },
  { value: "KRW", label: "South Korea - KRW" },
  { value: "KWD", label: "Kuwait - KWD" },
  { value: "KYD", label: "Cayman Islands - KYD" },
  { value: "KZT", label: "Kazakhstan - KZT" },
  { value: "LAK", label: "Lao People's Democratic Republic - LAK" },
  { value: "LBP", label: "Lebanon - LBP" },
  { value: "XCD", label: "Saint Lucia - XCD" },
  { value: "CHF", label: "Liechtenstein - CHF" },
  { value: "LKR", label: "Sri Lanka - LKR" },
  { value: "LRD", label: "Liberia - LRD" },
  { value: "LSL", label: "Lesotho - LSL" },
  { value: "EUR", label: "Lithuania - EUR" },
  { value: "EUR", label: "Luxembourg - EUR" },
  { value: "EUR", label: "Latvia - EUR" },
  { value: "LYD", label: "Libya - LYD" },
  { value: "MAD", label: "Morocco - MAD" },
  { value: "EUR", label: "Monaco - EUR" },
  { value: "MDL", label: "Moldova, Republic of - MDL" },
  { value: "EUR", label: "Montenegro - EUR" },
  { value: "EUR", label: "Saint Martin (French part) - EUR" },
  { value: "MGA", label: "Madagascar - MGA" },
  { value: "USD", label: "Marshall Islands - USD" },
  { value: "MKD", label: "The Republic of North Macedonia - MKD" },
  { value: "XOF", label: "Mali - XOF" },
  { value: "MMK", label: "Myanmar - MMK" },
  { value: "MNT", label: "Mongolia - MNT" },
  { value: "MOP", label: "Macao - MOP" },
  { value: "USD", label: "Northern Mariana Islands - USD" },
  { value: "EUR", label: "Martinique - EUR" },
  { value: "MRO", label: "Mauritania - MRO" },
  { value: "XCD", label: "Montserrat - XCD" },
  { value: "EUR", label: "Malta - EUR" },
  { value: "MUR", label: "Mauritius - MUR" },
  { value: "MVR", label: "Maldives - MVR" },
  { value: "MWK", label: "Malawi - MWK" },
  { value: "MXN", label: "Mexico - MXN" },
  { value: "MYR", label: "Malaysia - MYR" },
  { value: "MZN", label: "Mozambique - MZN" },
  { value: "NAD", label: "Namibia - NAD" },
  { value: "XPF", label: "New Caledonia - XPF" },
  { value: "XOF", label: "Niger - XOF" },
  { value: "AUD", label: "Norfolk Island - AUD" },
  { value: "NGN", label: "Nigeria - NGN" },
  { value: "NIO", label: "Nicaragua - NIO" },
  { value: "EUR", label: "Netherlands - EUR" },
  { value: "NOK", label: "Norway - NOK" },
  { value: "NPR", label: "Nepal - NPR" },
  { value: "AUD", label: "Nauru - AUD" },
  { value: "NZD", label: "Niue - NZD" },
  { value: "NZD", label: "New Zealand - NZD" },
  { value: "OMR", label: "Oman - OMR" },
  { value: "PAB", label: "Panama - PAB" },
  { value: "PEN", label: "Peru - PEN" },
  { value: "XPF", label: "French Polynesia - XPF" },
  { value: "PGK", label: "Papua New Guinea - PGK" },
  { value: "PHP", label: "Philippines - PHP" },
  { value: "PKR", label: "Pakistan - PKR" },
  { value: "PLN", label: "Poland - PLN" },
  { value: "EUR", label: "Saint Pierre and Miquelon - EUR" },
  { value: "NZD", label: "Pitcairn - NZD" },
  { value: "USD", label: "Puerto Rico - USD" },
  { value: "ILS", label: "State of Palestine - ILS" },
  { value: "EUR", label: "Portugal - EUR" },
  { value: "USD", label: "Palau - USD" },
  { value: "PYG", label: "Paraguay - PYG" },
  { value: "QAR", label: "Qatar - QAR" },
  { value: "EUR", label: "Reunion - EUR" },
  { value: "RON", label: "Romania - RON" },
  { value: "RSD", label: "Serbia - RSD" },
  { value: "RUB", label: "Russian Federation - RUB" },
  { value: "RWF", label: "Rwanda - RWF" },
  { value: "SAR", label: "Saudi Arabia - SAR" },
  { value: "SBD", label: "Solomon Islands - SBD" },
  { value: "SCR", label: "Seychelles - SCR" },
  { value: "SDG", label: "Sudan - SDG" },
  { value: "SEK", label: "Sweden - SEK" },
  { value: "SGD", label: "Singapore - SGD" },
  { value: "SHP", label: "Saint Helena - SHP" },
  { value: "EUR", label: "Slovenia - EUR" },
  { value: "NOK", label: "Svalbard and Jan Mayen - NOK" },
  { value: "EUR", label: "Slovakia - EUR" },
  { value: "SLL", label: "Sierra Leone - SLL" },
  { value: "EUR", label: "San Marino - EUR" },
  { value: "XOF", label: "Senegal - XOF" },
  { value: "SOS", label: "Somalia - SOS" },
  { value: "SRD", label: "Suriname - SRD" },
  { value: "STD", label: "Sao Tome and Principe - STD" },
  { value: "SVC", label: "El Salvador - SVC" },
  { value: "ANG", label: "Sint Maarten (Dutch part) - ANG" },
  { value: "SYP", label: "Syrian Arab Republic - SYP" },
  { value: "SZL", label: "Eswatini - SZL" },
  { value: "USD", label: "Turks and Caicos Islands - USD" },
  { value: "XAF", label: "Chad - XAF" },
  { value: "EUR", label: "French Southern Territories - EUR" },
  { value: "XOF", label: "Togo - XOF" },
  { value: "THB", label: "Thailand - THB" },
  { value: "TJS", label: "Tajikistan - TJS" },
  { value: "NZD", label: "Tokelau - NZD" },
  { value: "USD", label: "Timor-Leste - USD" },
  { value: "TMT", label: "Turkmenistan - TMT" },
  { value: "TND", label: "Tunisia - TND" },
  { value: "TOP", label: "Tonga - TOP" },
  { value: "TRY", label: "Turkey - TRY" },
  { value: "TTD", label: "Trinidad and Tobago - TTD" },
  { value: "AUD", label: "Tuvalu - AUD" },
  { value: "TWD", label: "Taiwan, Province of China - TWD" },
  { value: "TZS", label: "United Republic of Tanzania - TZS" },
  { value: "UAH", label: "Ukraine - UAH" },
  { value: "UGX", label: "Uganda - UGX" },
  { value: "USD", label: "United States Minor Outlying Islands - USD" },
  { value: "USD", label: "United States of America - USD" },
  { value: "UYU", label: "Uruguay - UYU" },
  { value: "UZS", label: "Uzbekistan - UZS" },
  { value: "EUR", label: "Holy See (Vatican City State) - EUR" },
  { value: "XCD", label: "Saint Vincent and the Grenadines - XCD" },
  { value: "VEF", label: "Venezuela - VEF" },
  { value: "USD", label: "Virgin Islands, British - USD" },
  { value: "USD", label: "Virgin Islands, U.S. - USD" },
  { value: "VND", label: "Vietnam - VND" },
  { value: "VUV", label: "Vanuatu - VUV" },
  { value: "XPF", label: "Wallis and Futuna - XPF" },
  { value: "WST", label: "Samoa - WST" },
  { value: "YER", label: "Yemen - YER" },
  { value: "EUR", label: "Mayotte - EUR" },
  { value: "ZAR", label: "South Africa - ZAR" },
  { value: "ZMW", label: "Zambia - ZMW" },
  { value: "ZWL", label: "Zimbabwe - ZWL" }
];